### ISSUE TITLE
[ERROR] [UrlShortenerService] E-mail is not defined

### ISSUE THREAD

**Issue by Wolgrand** [FelippeChemello/podcast-maker#4]
Hey Felipe. Parabéns pelo projeto. Estou com o erro :

`[ERROR] [UrlShortenerService] E-mail is not defined` Que serviço é esse JAUS? Pode me informar onde eu crio o registro ?

Obrigado

**Comment by FelippeChemello** [comment]
Obrigado.

JAUS é um projeto que ainda está em fase de desenvolvimento. Para sanar este erro você pode retomar a implementação deste service para [este](https://github.com/FelippeChemello/podcast-maker/blob/9d1dd3038ccc2deb54101dd0d28a5ad50f678b4d/src/services/UrlShortenerService.ts), adicionando também as variáveis de ambiente que estão no construtor ao seu `.env` e alterando o rebrandlyWorkspaceId para um de sua conta. 
Nesta implementação estava utilizando a plataforma rebrandly.

Porém algo mais simples, caso você não precise de um encurtado de link neste momento é simplesmente comentar a chamada deste service no `options.ts` (`await new UrlShortenerService(content).execute();`) os demais serviços não são dependentes deste e todas as demais funções devem continuar funcionando.
