### ISSUE TITLE
Não consegui rodar no windows

### ISSUE THREAD

**Issue by matefs** [FelippeChemello/podcast-maker#536]
Segue a lista de comandos que eu rodei:
$ git clone https://github.com/FelippeChemello/podcast-maker.git

$ yarn
 
$ yarn build

Para startar o serviço eu preciso utilizar um servidor http na pasta dist  ?

**Comment by FelippeChemello** [comment]
Após configurar com `./bin/run configure` basta executar `./bin/run create`

**Comment by matefs** [comment]
Agora entendi um pouco, o comando `./bin/run configure`  serve para simular um CLI dentro do próprio repositório, através dele rodamos  o `configure` e `create`.
