### ISSUE TITLE
JAUS Autentication

### ISSUE THREAD

**Issue by Pride7K** [FelippeChemello/podcast-maker#6]
Cara, poderia me ajudar com essa questão, não consigo localizar onde devo criar este "JAUS", na url onde é feito o post não é possivel criar nenhum tipo de credencial ou algo do tipo.

**Comment by davidnetto** [comment]
I have the same problem

**Comment by FelippeChemello** [comment]
JAUS é um projeto que ainda está em fase de desenvolvimento. Para sanar este erro você pode retomar a implementação deste service para este, adicionando também as variáveis de ambiente que estão no construtor ao seu .env e alterando o rebrandlyWorkspaceId para um de sua conta.
Nesta implementação estava utilizando a plataforma rebrandly.

Porém algo mais simples, caso você não precise de um encurtado de link neste momento é simplesmente comentar a chamada deste service no options.ts (await new UrlShortenerService(content).execute();) os demais serviços não são dependentes deste e todas as demais funções devem continuar funcionando.
