### ISSUE TITLE
Instagram videos without voice

### ISSUE THREAD

**Issue by Muurilo** [FelippeChemello/podcast-maker#7]
Voice not working, i get this error while build the video.

[Error: Error: Cannot find module './C:\Users\Murilo\Documents\Projects\podcast-maker\tmp\output-0.mp3'
    at webpackContextResolve (http://localhost:3000/bundle.js:13195:11)
    at webpackContext (http://localhost:3000/bundle.js:13190:11)
    at loadAudio (http://localhost:3000/bundle.js:13440:41)
    at http://localhost:3000/bundle.js:13452:5
    at fk (http://localhost:3000/bundle.js:6938:19)
    at exports.unstable_runWithPriority (http://localhost:3000/bundle.js:11950:12)
    at gg (http://localhost:3000/bundle.js:3787:10)
    at Oj (http://localhost:3000/bundle.js:6890:12)
    at http://localhost:3000/bundle.js:6880:7
    at V (http://localhost:3000/bundle.js:11876:17)]

the intro sound works fine

**Comment by Muurilo** [comment]
I created the TTS

**Comment by FelippeChemello** [comment]
It seams like output for news was not created, please check content file and TTS process. 
It expect to have output-X.mp3 created in tmp directory

**Comment by Muurilo** [comment]
I have all these files inside temp dir 
![image](https://user-images.githubusercontent.com/46500752/117705542-8d65a800-b1a2-11eb-9ec6-898249de2b9f.png)

**Comment by Muurilo** [comment]
it looks like it has a ./ at start of path, maybe this is an error?

**Comment by FelippeChemello** [comment]
Yes, I have only tested on Linux, as you are using windows path could not be right.

Try to remove it and feel free to send a PR correcting it

**Comment by Muurilo** [comment]
how i can generate a file like example .json inside temp folder?

**Comment by Muurilo** [comment]
The problem is in the file generated in the temp folder similar to example.json, the path to the audio is with the wrong formatting just like you said, but I can't find where the file is generated to change the path

**Comment by FelippeChemello** [comment]
This file is exported at `ExportDataService.ts`, however audio file path is defined in `content.json` at `RetrieveAudioDataService.ts`

**Comment by FelippeChemello** [comment]
t

**Comment by Muurilo** [comment]
Yes.

**Comment by Muurilo** [comment]
Pls, remove --props inline json and add to a file because windows not support this

**Comment by Muurilo** [comment]
When are you going to make the changes and approve the PR

**Comment by FelippeChemello** [comment]
I will take a look at it during the weekend

**Comment by FelippeChemello** [comment]
I need to make some changes in your PR, it seems like doesn't correct the root of problem... I was investigating, cause it seems to have a bug in motion require

**Comment by FelippeChemello** [comment]
UPDATE: still working in this issue, asap I will be back with bug correction

**Comment by Muurilo** [comment]
ok, thanks for the support

**Comment by FelippeChemello** [comment]
fix was merged on https://github.com/FelippeChemello/podcast-maker/pull/10
