### ISSUE TITLE
JAUS Autentication

### ISSUE THREAD

**Issue by Pride7K** [FelippeChemello/podcast-maker#8]
I'm having trouble with JAUS Autentatication, need credentials.

**Comment by davidnetto** [comment]
I have the same problem .. wtf é JAUS???

**Comment by Muurilo** [comment]
JAUS i think is this https://github.com/FelippeChemello/Just-Another-URL-Shortener

maybe need to run this?

**Comment by FelippeChemello** [comment]
Yes, JAUS is that project, however it haven't been deployed yet. 
So to continue using podcast-maker you can only disable call for this service (comment `await new UrlShortenerService(content).execute()` in `options.ts`)
